http-read-header-timeout: 0s
query-concurrency: 100
query-initial-memory-bytes: 104857600
query-memory-bytes: 104857600
query-max-memory-bytes: 10485760000
query-queue-size: 100
nats-max-payload-bytes: 1073741824
storage-cache-max-memory-size: 5368709120
storage-cache-snapshot-memory-size: 1073741824
bolt-path: /data/.influxdbv2/influxd.bolt
engine-path: /data/.influxdbv2/engine