{
 "title": "Server Monitor",
 "time": { "from": "2019-10-29T08:28:13.469Z", "to": "2019-10-29T09:57:07.378Z" },
 "panels": [
  {
   "title": "Network Traffic",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "KBs" }
   ],
   "targets": [
    { "target": "test._06.NETWORK_R_RATE", "type": "timeserie" },
    { "target": "test._06.NETWORK_S_RATE", "type": "timeserie" }
   ]
  },
  {
   "title": "System Resource Usage",
   "type": "graph",
   "description": "The results are based on the iostat command",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    { "target": "test._06.MEM_USAGE", "type": "timeserie" },
    { "target": "test._06.CPU_USAGE", "type": "timeserie" },
    { "target": "test._06.DISK_IO_USAGE", "type": "timeserie" }
   ]
  },
  {
   "title": "DB Service Process Memory Consumption",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "decgbytes" }
   ],
   "targets": [
    { "target": "test._06.PROCESS_MEM_SIZE", "type": "timeserie" }
   ]
  },
  {
   "title": "Disk I/O TPS ",
   "type": "graph",
   "description": "I/O request per second",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    { "target": "test._06.DISK_TPS", "type": "timeserie" }
   ]
  },
  {
   "title": "Directories File Size Monitor",
   "type": "graph",
   "description": "-1 stands for that the corresponding directory does not exist",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 15 },
   "yaxes": [
    { "format": "decgbytes" }
   ],
   "targets": [
    { "target": "test._06.DATA_FILE_SIZE", "type": "timeserie" },
    { "target": "test._06.SEQUENCE_FILE_SIZE", "type": "timeserie" },
    { "target": "test._06.SYSTEM_FILE_SIZE", "type": "timeserie" },
    { "target": "test._06.UN_SEQUENCE_FILE_SIZE", "type": "timeserie" },
    { "target": "test._06.WAL_FILE_SIZE", "type": "timeserie" }
   ]
  },
  {
   "title": "Disk Read and Write Speed (MB/s)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 15 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "target": "test._06.DISK_READ_SPEED_MB", "type": "timeserie" },
    { "target": "test._06.DISK_WRITE_SPEED_MB", "type": "timeserie" }
   ]
  },
  {
   "title": "System Resource Usage",
   "type": "gauge",
   "description": "The results are based on the iostat command",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 22 },
   "targets": [
    { "target": "test._06.MEM_USAGE", "type": "timeserie" },
    { "target": "test._06.CPU_USAGE", "type": "timeserie" },
    { "target": "test._06.DISK_IO_USAGE", "type": "timeserie" }
   ]
  }
 ]
}