{
 "title": "Ingestion Test",
 "time": { "from": "2019-10-24T14:40:57.874Z", "to": "2019-10-24T14:41:09.991Z" },
 "panels": [
  {
   "title": "Operation Latency in Millisecond",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short", "label": "Latency (ms)" }
   ],
   "targets": [
    {
     "target": "test.IoTDB__2019_10_24_10_40_58_362.pool-1-thread-1.INGESTION.latency",
     "type": "timeserie"
    }
   ]
  },
  {
   "title": "Latency Heat Map",
   "type": "heatmap",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "target": "test.IoTDB__2019_10_24_10_40_58_362.pool-1-thread-1.INGESTION.latency",
     "type": "timeserie"
    }
   ]
  },
  {
   "title": "History Ingestion Operation Result",
   "type": "table",
   "description": "The timestamp of each row is the start time of the test.\nThe unit of throughput is points/s",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 9 },
   "targets": [
    { "target": "test.INGESTION.okOperationNum", "type": "timeserie" },
    { "target": "test.INGESTION.okPointNum", "type": "timeserie" },
    {
     "target": "test.INGESTION.failOperationNum",
     "type": "timeserie"
    },
    { "target": "test.INGESTION.failPointNum", "type": "timeserie" },
    { "target": "test.INGESTION.throughput", "type": "timeserie" },
    { "target": "test.total.createSchemaTime", "type": "timeserie" },
    { "target": "test.total.elapsedTime", "type": "timeserie" }
   ]
  },
  {
   "title": "Latency Statistics",
   "type": "table",
   "description": "MID_AVG is the AVG without the 5% data of the head and the tail.",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 15 },
   "targets": [
    { "target": "test.INGESTION.MIN", "type": "timeserie" },
    { "target": "test.INGESTION.AVG", "type": "timeserie" },
    { "target": "test.INGESTION.MID_AVG", "type": "timeserie" },
    { "target": "test.INGESTION.MEDIAN", "type": "timeserie" },
    { "target": "test.INGESTION.P90", "type": "timeserie" },
    { "target": "test.INGESTION.P95", "type": "timeserie" },
    { "target": "test.INGESTION.P99", "type": "timeserie" },
    { "target": "test.INGESTION.MAX", "type": "timeserie" },
    { "target": "test.INGESTION.SLOWEST_THREAD", "type": "timeserie" }
   ]
  },
  { "title": "Row title", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 22 } }
 ]
}